### ISSUE TITLE
Sentence case exceptions don't work after special characters

### ISSUE THREAD

**Issue by melissaanderegg** [stelter/StelterAPI#19]
Given the following title: "Donor MultiCare recognition: MultiCare legacy circle" (x680929)

with the following exception: "MultiCare"

output: "Donor MultiCare recognition: Multicare legacy circle"

The instance of the exception after the colon ":" doesn't work.

**Comment by PaulSearcy** [comment]
This is a limitation of the algorithm used to perform sentence casing

```js 
let change = string
            .toLowerCase()
            // eslint-disable-next-line no-useless-escape
            .split(/([\?\.\!\:])+/g) 
            .map(section =>{
                let precedingWhiteSpace = section.length - section.replace(/^\s+/, '').length
                return ' '.repeat(precedingWhiteSpace) + section.charAt(precedingWhiteSpace).toUpperCase() + section.slice(precedingWhiteSpace + 1)
            })
            .join(``)

// This must go first of all the special cases because it deals with an edge case of the regex splitting on periods PS 05/17/2018
        change.indexOf('vs.') != -1 ? change = change.split('vs.').map((x,index) => index == 1 ? x.toLowerCase() : x ).join('vs.') : null
```

In the code above the 'split' call is what is splitting the string into an array based on . ? ! or :

To get around this in a certain case I had to right an exception which is the last part of the code above. 

For cases with any of those special characters we will have to add special cases or rewrite this function and test that it works with all existing cases.

**Comment by chrisbutzke** [comment]
I haven't taken a deep dive on this, but wouldn't removing ":" from the split regex fix the issue?

**Comment by chrisbutzke** [comment]
This was included in pull request 79 https://github.com/stelter/StelterAPI/pull/73
